# Site settings
title: Budo Notes

author:
  name: Rickard von Haugwitz
  email: rickardvh@gmail.com
  github: rickardvh

description: >-
  Notes on iaido, jodo, and kendo kata.
url: "https://rickardvh.github.io"

links_to_prev_next: true

# Build settings
markdown: GFM
permalink: /:title
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
