# Site settings
title: Rickard's Budo Notes
author: Rickard von Haugwitz
email: rickardvh@gmail.com
description: >
  Notes on iaido, jodo, and kendo kata.
github_username:  rickardvh

# Build settings
markdown: GFM
permalink: /:year/:title:output_ext
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
